# Generated by Django 5.0.14 on 2026-09-25 15:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropertySource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True)),
                ('source_type', models.CharField(choices=[('AGENCY_PARTNER_API', 'Agency/Agency-network partner API'), ('REGULATORY_REGISTRY', 'Regulatory body public registry'), ('LISTING_PARTNER_FEED', 'Authorized listing partner feed'), ('MANUAL', 'Manual entry (admin/ops)'), ('PUBLIC_DATA', 'Permitted public dataset')], max_length=32)),
                ('ingestion_method', models.CharField(choices=[('API', 'API integration'), ('AUTHORIZED_FEED', 'Authorized feed (RSS/XML/CSV export etc.)'), ('PARTNER_FEED', 'Partner feed under agreement'), ('MANUAL_ENTRY', 'Manual entry by admin/ops'), ('PERMITTED_PUBLIC_DATA', 'Permitted public data (e.g. open registry)'), ('APPROVED_METADATA', 'Approved public page metadata (structured data the source publishes for reuse)')], max_length=32)),
                ('permission_status', models.CharField(choices=[('PENDING_REVIEW', 'Pending legal/ops review'), ('AUTHORIZED', 'Authorized'), ('REVOKED', 'Revoked'), ('NOT_AUTHORIZED', 'Not authorized (do not ingest)')], default='PENDING_REVIEW', max_length=20)),
                ('terms_notes', models.TextField(blank=True, help_text='Notes on terms of use / partnership agreement covering this source. Attach or link the agreement where possible.')),
                ('contact_email', models.EmailField(blank=True, help_text='Contact at the source for partnership/authorization matters.', max_length=254)),
                ('is_active', models.BooleanField(default=False)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('next_sync_at', models.DateTimeField(blank=True, null=True)),
                ('sync_frequency_minutes', models.PositiveIntegerField(blank=True, help_text='How often this source should be re-synced, in minutes.', null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
