# Generated by Django 5.0.14 on 2026-09-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertysource',
            name='adapter',
            field=models.CharField(blank=True, choices=[('', 'None (manual entry only)'), ('propertyspot', 'PropertySpot public listings API')], default='', help_text='Which ingestion adapter (apps/sources/ingestion) syncs this source. Blank = manual entry only.', max_length=32),
        ),
    ]
