# Generated by Django 5.0.14 on 2026-09-25 15:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('check_type', models.CharField(choices=[('ESVARBON', 'ESVARBON (Estate Surveyors & Valuers)'), ('LASRERA', 'LASRERA (Lagos State Real Estate Regulatory Authority)'), ('CAC', 'CAC (Corporate Affairs Commission)'), ('CONTACT_PHONE', 'Contact — phone'), ('CONTACT_EMAIL', 'Contact — email'), ('WEBSITE', 'Website'), ('MANUAL_REVIEW', 'General manual review')], max_length=20)),
                ('method', models.CharField(choices=[('AUTOMATED_API', 'Automated API integration'), ('MANUAL_PORTAL_CHECK', 'Manual check of an official portal/registry'), ('MANUAL_CONTACT', 'Manual contact (call/email) with agency or regulator'), ('DOCUMENT_REVIEW', 'Document review')], max_length=24)),
                ('source', models.CharField(help_text="Where the check was performed, e.g. 'https://portal.esvarbon.gov.ng/pages/verify' or 'Phone call to agency'.", max_length=255)),
                ('result', models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('INCONCLUSIVE', 'Inconclusive'), ('NOT_APPLICABLE', 'Not applicable')], max_length=16)),
                ('registration_number', models.CharField(blank=True, help_text='Registration/licence number checked, if applicable.', max_length=64)),
                ('subject_name', models.CharField(blank=True, help_text='Practitioner/firm name as checked against the registry.', max_length=255)),
                ('evidence_reference', models.TextField(blank=True, help_text='Reference/evidence supporting the result: screenshot filename, reference number, saved copy link, etc.')),
                ('evidence_file', models.FileField(blank=True, null=True, upload_to='verification_evidence/')),
                ('notes', models.TextField(blank=True)),
                ('checked_at', models.DateTimeField(help_text='When the check was actually performed (may differ from created_at).')),
                ('expiration_date', models.DateField(blank=True, help_text="When this check's result should be treated as stale.", null=True)),
                ('recheck_date', models.DateField(blank=True, help_text='When this check should next be performed.', null=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_checks', to='agencies.agency')),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_checks_performed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='RegulatoryRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('regulator', models.CharField(choices=[('ESVARBON', 'ESVARBON'), ('LASRERA', 'LASRERA'), ('CAC', 'CAC')], max_length=16)),
                ('registration_number', models.CharField(max_length=64)),
                ('subject_name', models.CharField(blank=True, max_length=255)),
                ('status_on_registry', models.CharField(blank=True, help_text='Status as shown on the official registry, verbatim where possible.', max_length=100)),
                ('raw_reference', models.TextField(blank=True, help_text='Verbatim notes/reference captured from the official source.')),
                ('source_url', models.URLField(blank=True)),
                ('checked_at', models.DateTimeField()),
                ('verification_check', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regulatory_records', to='verification.verificationcheck')),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
        migrations.AddIndex(
            model_name='verificationcheck',
            index=models.Index(fields=['agency', 'check_type'], name='verificatio_agency__282b2d_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationcheck',
            index=models.Index(fields=['result'], name='verificatio_result_77998f_idx'),
        ),
        migrations.AddIndex(
            model_name='regulatoryrecord',
            index=models.Index(fields=['regulator', 'registration_number'], name='verificatio_regulat_0e853a_idx'),
        ),
    ]
