# Generated by Django 5.0.14 on 2026-09-25 15:45

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0001_initial'),
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('property_type', models.CharField(choices=[('APARTMENT', 'Apartment'), ('HOUSE', 'House'), ('DUPLEX', 'Duplex'), ('BUNGALOW', 'Bungalow'), ('TERRACE', 'Terrace'), ('LAND', 'Land'), ('SHORTLET', 'Shortlet'), ('COMMERCIAL', 'Commercial'), ('OTHER', 'Other')], max_length=20)),
                ('transaction_type', models.CharField(choices=[('RENT', 'Rent'), ('BUY', 'Buy'), ('SHORTLET', 'Shortlet')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='NGN', max_length=8)),
                ('price_period', models.CharField(blank=True, help_text="e.g. 'year', 'month', 'night' for rent/shortlet pricing.", max_length=20)),
                ('location', models.CharField(help_text="Free-text area/neighbourhood, e.g. 'Lekki Phase 1'.", max_length=255)),
                ('state', models.CharField(default='Lagos', max_length=100)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('area', models.CharField(blank=True, max_length=150)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('bedrooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bathrooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('toilets', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('amenities', models.JSONField(blank=True, default=list, help_text="List of amenity strings, e.g. ['pool', 'gym', '24/7 power'].")),
                ('furnished_status', models.CharField(choices=[('FURNISHED', 'Furnished'), ('SEMI_FURNISHED', 'Semi-furnished'), ('UNFURNISHED', 'Unfurnished'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('source_url', models.URLField(blank=True)),
                ('source_property_id', models.CharField(blank=True, help_text="The property's ID/reference on the source system, if any.", max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PENDING_REVIEW', 'Pending review'), ('STALE', 'Stale / needs recheck'), ('REMOVED', 'Removed')], default='PENDING_REVIEW', max_length=20)),
                ('verification_status', models.CharField(choices=[('SOURCE_CONFIRMED', 'Source confirmed'), ('AGENCY_PROVIDED', 'Agency provided'), ('INDEPENDENTLY_VERIFIED', 'Independently verified'), ('PENDING_REVIEW', 'Pending review'), ('REMOVED', 'Removed'), ('STALE', 'Stale')], default='AGENCY_PROVIDED', max_length=30)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('last_checked_at', models.DateTimeField(blank=True, help_text='Last time we actively re-confirmed this listing.', null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, help_text='Last time the source still showed this listing as available.', null=True)),
                ('live_viewing_available', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, null=True)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='agencies.agency')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='sources.propertysource')),
            ],
            options={
                'verbose_name_plural': 'properties',
                'ordering': ['-discovered_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='NGN', max_length=8)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='properties.property')),
            ],
            options={
                'verbose_name_plural': 'price history',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='property_images/')),
                ('display_authorized', models.BooleanField(default=False, help_text='Must be explicitly true before this image is served publicly.')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['status'], name='properties__status_6427a0_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['verification_status'], name='properties__verific_060ad3_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['property_type', 'transaction_type'], name='properties__propert_363fab_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['state', 'city', 'area'], name='properties__state_daaec7_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['price'], name='properties__price_32e7c2_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='properties__search__940c9d_gin'),
        ),
    ]
