# Generated by Django 5.0.14 on 2026-09-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyimage',
            name='external_url',
            field=models.URLField(blank=True, help_text='Image hosted by the source (used for ingested listings instead of copying the file).', max_length=1000),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='property_images/'),
        ),
    ]
