# Generated by Django 5.0.14 on 2026-09-30 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_propertyimage_external_url_alter_propertyimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='listed_at',
            field=models.DateTimeField(blank=True, help_text='When the listing was first posted (on the source, for ingested listings). Listings older than LISTING_MAX_AGE_DAYS are hidden as stale; set this to today to renew a listing the agent has re-confirmed.', null=True),
        ),
    ]
