# Generated by Django 5.0.14 on 2026-09-25 15:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0001_initial'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_name', models.CharField(max_length=150)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('customer_phone', models.CharField(blank=True, max_length=32)),
                ('message', models.TextField(blank=True)),
                ('source_channel', models.CharField(choices=[('PROPERTY_ENQUIRY_FORM', 'Property enquiry form'), ('CALL_CLICK', 'Call button click'), ('EMAIL_CLICK', 'Email button click'), ('WHATSAPP_CLICK', 'WhatsApp button click'), ('AGENCY_WEBSITE_CLICK', 'Visit agency website click'), ('LIVE_VIEWING_REQUEST', 'Live viewing request')], default='PROPERTY_ENQUIRY_FORM', max_length=32)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('SENT', 'Sent to agency'), ('CONTACTED', 'Agency contacted customer'), ('QUALIFIED', 'Qualified'), ('CLOSED', 'Closed'), ('INVALID', 'Invalid')], default='NEW', max_length=16)),
                ('consent_given', models.BooleanField(default=False, help_text='Customer consented to their contact details being shared with the agency.')),
                ('consent_timestamp', models.DateTimeField(blank=True, null=True)),
                ('referred_at', models.DateTimeField(blank=True, help_text='When the lead was actually sent to the agency.', null=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='agencies.agency')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='properties.property')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='leads_lead_status_e23abe_idx'), models.Index(fields=['agency', 'status'], name='leads_lead_agency__44a84e_idx')],
            },
        ),
    ]
