# Generated by Django 5.0.14 on 2026-09-25 15:45

import apps.live_viewing.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0001_initial'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyRepresentative',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representatives', to='agencies.agency')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LiveViewingRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_name', models.CharField(max_length=150)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('customer_phone', models.CharField(blank=True, max_length=32)),
                ('requested_date', models.DateField()),
                ('requested_time', models.TimeField(blank=True, help_text="Blank means 'earliest available'.", null=True)),
                ('customer_message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('PENDING_AGENT', 'Pending agent'), ('ACCEPTED', 'Accepted'), ('SCHEDULED', 'Scheduled'), ('LIVE', 'Live'), ('COMPLETED', 'Completed'), ('DECLINED', 'Declined'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No show'), ('FAILED', 'Failed')], default='REQUESTED', max_length=16)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('decline_reason', models.TextField(blank=True)),
                ('customer_access_token', models.CharField(default=apps.live_viewing.models.generate_token, editable=False, max_length=64, unique=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_viewing_requests', to='agencies.agency')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_viewing_requests', to='properties.property')),
                ('representative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_viewing_requests', to='live_viewing.agencyrepresentative')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LiveViewingEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(max_length=50)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('viewing_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='live_viewing.liveviewingrequest')),
            ],
            options={
                'ordering': ['occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='LiveViewingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_name', models.CharField(blank=True, help_text='Which real-time video provider (livekit/agora/daily/twilio) backs this session.', max_length=32)),
                ('provider_room_id', models.CharField(blank=True, max_length=255)),
                ('scheduled_start', models.DateTimeField()),
                ('scheduled_end', models.DateTimeField()),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('actual_end', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('LIVE', 'Live'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=16)),
                ('recording_enabled', models.BooleanField(default=False)),
                ('consent_recorded_at', models.DateTimeField(blank=True, null=True)),
                ('participant_info', models.JSONField(blank=True, default=dict, help_text='Non-sensitive join metadata, e.g. join/leave timestamps per role.')),
                ('viewing_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='live_viewing.liveviewingrequest')),
            ],
            options={
                'ordering': ['-scheduled_start'],
            },
        ),
        migrations.AddIndex(
            model_name='liveviewingrequest',
            index=models.Index(fields=['status'], name='live_viewin_status_5689b0_idx'),
        ),
        migrations.AddIndex(
            model_name='liveviewingrequest',
            index=models.Index(fields=['agency', 'status'], name='live_viewin_agency__9b5305_idx'),
        ),
    ]
