# Generated by Django 5.0.14 on 2026-09-25 15:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='agency_logos/')),
                ('logo_display_authorized', models.BooleanField(default=False, help_text='Only show the logo publicly once we have permission to display it.')),
                ('website', models.URLField(blank=True)),
                ('phone_number', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('whatsapp_number', models.CharField(blank=True, max_length=32)),
                ('business_address', models.CharField(blank=True, max_length=500)),
                ('service_locations', models.JSONField(blank=True, default=list, help_text='List of area/city names served.')),
                ('cac_registration_number', models.CharField(blank=True, max_length=64)),
                ('esvarbon_registration_number', models.CharField(blank=True, max_length=64)),
                ('lasrera_registration_number', models.CharField(blank=True, max_length=64)),
                ('verification_status', models.CharField(choices=[('DISCOVERED', 'Discovered'), ('PENDING_REVIEW', 'Pending review'), ('VERIFICATION_IN_PROGRESS', 'Verification in progress'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended'), ('EXPIRED_RECHECK_REQUIRED', 'Expired / recheck required')], default='DISCOVERED', max_length=32)),
                ('verification_recheck_date', models.DateField(blank=True, null=True)),
                ('phone_status', models.CharField(choices=[('NOT_PROVIDED', 'Not provided'), ('PROVIDED', 'Provided'), ('VERIFIED', 'Verified'), ('FAILED', 'Failed')], default='NOT_PROVIDED', max_length=16)),
                ('email_status', models.CharField(choices=[('NOT_PROVIDED', 'Not provided'), ('PROVIDED', 'Provided'), ('VERIFIED', 'Verified'), ('FAILED', 'Failed')], default='NOT_PROVIDED', max_length=16)),
                ('website_status', models.CharField(choices=[('NOT_PROVIDED', 'Not provided'), ('EXISTS', 'Exists'), ('ACCESSIBLE', 'Accessible'), ('MATCHES_IDENTITY', 'Matches agency identity'), ('FAILED', 'Failed')], default='NOT_PROVIDED', max_length=20)),
                ('is_suspended', models.BooleanField(default=False)),
                ('suspension_reason', models.TextField(blank=True)),
                ('sources', models.ManyToManyField(blank=True, related_name='agencies', to='sources.propertysource')),
            ],
            options={
                'verbose_name_plural': 'agencies',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['verification_status'], name='agencies_ag_verific_ff1de1_idx'), models.Index(fields=['slug'], name='agencies_ag_slug_a791c8_idx')],
            },
        ),
    ]
