# Generated by Django 5.0.14 on 2026-09-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='source_agency_id',
            field=models.CharField(blank=True, help_text="The agency's/agent's ID on the source it was ingested from, used to avoid duplicates on re-sync.", max_length=255),
        ),
    ]
